// ⚠  TEMPLATE FILE — DO NOT COMMIT REAL CREDENTIALS ⚠
//
// This file is a *template* for the values generated by the FlutterFire CLI:
//   https://firebase.flutter.dev/docs/cli
//
// To configure your Firebase project:
//   1. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
//   2. Run:                       flutterfire configure
//   3. The CLI will overwrite this file with your real values.
//
// NEVER commit this file after it contains real API keys.
// Add it to .gitignore once real values have been filled in:
//   echo "lib/firebase_options.dart" >> .gitignore
//
// All values below are non-functional placeholders.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Reconfigure with flutterfire configure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---------------------------------------------------------------------------
  // Replace ALL placeholder values below with your real Firebase config.
  // ---------------------------------------------------------------------------

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.iotmanager.app',
  );
}
